name: TagPublish

on:
  release:
    types: [published]
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="MedabotsRandomizer-$tag-win-x64"

          # Build everything
          dotnet publish --framework net6.0 --runtime "win-x64" -c Release -o "$release_name"

          # Pack files
          # Pack to zip for Windows
          7z a -tzip "${release_name}.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "MedabotsRandomizer*"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASEWORKFLOW }}
